### ISSUE TITLE
Fix broken user message handling

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#107]
Task is to fix display of user messages from the server.

Display of messages sent from server to user (displayed in the Workbench) is broken in Beta 1. Functionality was broken by commit: https://github.com/evothings/evothings-studio/commit/4e9aa8dc2eaf6df3379b11da6a7dae951e20df67#diff-548b1e556f3ac1680e94a48722de28aa

**Comment by psvensson** [comment]
Fixed regression and added tab switch to connect tab (so the message is seen)
