### ISSUE TITLE
Fully logout from auth0

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#108]
Currently a logged in user is not fully logged out once logged in. This means that if another persons uses the machine, she can login as the previous user without authentication (for GitHub and Google+ accounts), and she cannot login herself.

A way to fully logout is needed.

**Comment by psvensson** [comment]
It turned out that Fredrik was correct and it was indeed quite simple. When logging out of the workbench you get the option of changing user when logging in again.
