### ISSUE TITLE
Investigate support for common design patterns regarding state preservation

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#11]
EvoThings Studio and HyperReload currently supports state preservation at refresh through handling of fragment identifiers.

Investigate common design patterns regarding state preservation by looking at what common frameworks recommends and how they are usually used. For example, investigate Backbone.js.

One obvious method of keeping track of state in an application is to store it in variables and dynamic DOM and Stylesheet modifications. For preserving the application's state at page refresh in this case, one idea is to let the entire JavaScript engine state be preserved. This could introduce unexpected behavior. A better idea is to track/record the engine's actions after page load and then at page refresh repeat those actions, but this likely requires much more development work.

**Comment by fredrikeldh** [comment]
Incompatible with Cordova and its plugins.
