### ISSUE TITLE
Rename Autoscroll on to "Pause Log"

### ISSUE THREAD

**Issue by gokr** [evothings/evothings-studio#132]
IMHO it more clearly explains what it actually does :)

**Comment by mikaelkindborg** [comment]
Also fix glitch with an extra blank line when resuming an active log stream.

**Comment by mikaelkindborg** [comment]
Time Estimate: 1h

**Comment by mikaelkindborg** [comment]
Button name and the extra newline fixed by this commit: https://github.com/evothings/evothings-studio/commit/8a4123f8f593c726e972baab87ef10da72865d3e
