### ISSUE TITLE
Function to disconnect connected Viewers

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#135]
This is needed for example after giving a customer demo. Then the customer's phone should be possible to disconnect so that she does not get the connect buttons.

This also requires at least a button in the Evothings Workbench UI to log out connected Viewers. Selective logout could also be implemented.

**Comment by psvensson** [comment]
See also https://github.com/evothings/evothings-server/issues/33

**Comment by mikaelkindborg** [comment]
A function that disconnects all viewers could be implemented as a menu option under the "More" menu or a button in the Settings dialog. This would be much quicker to implement than full-blown client management UI and provide essential functionality missing right now.

**Comment by gokr** [comment]
Just needs testing

**Comment by mikaelkindborg** [comment]
Added back menu option in this commit: https://github.com/evothings/evothings-studio/commit/229b3d7d2b4c040d93bb0d041ce183233318cfa6
