### ISSUE TITLE
Test that Evothings Studio 2.0 works with custom Cordova projects

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#138]
Problems have been reported when using Evothings Studio 2.0 with a custom Cordova app (cordova.js not found). Investigate this. Also update documentation for how to connect from a custom Cordova app to Evothings Workbench.

**Comment by mikaelkindborg** [comment]
Possibly related issue: 
https://github.com/evothings/evothings-studio/issues/90

**Comment by mikaelkindborg** [comment]
Done testing and status is that connecting from a custom Cordova app currently does not work.

Problems:

* In function serveCordovaFile() parameter `platform` is false. It should be a string with the current platform. This value comes from the server. https://github.com/evothings/evothings-studio/blob/2.1.0a2/hyper/server/file-server.js#L410

* Path composition in serveCordovaFile() does not work any longer, mBasePath seems now to not end with a slash. See these lines: https://github.com/evothings/evothings-studio/blob/2.1.0a2/hyper/server/file-server.js#L436, https://github.com/evothings/evothings-studio/blob/2.1.0a2/hyper/server/file-server.js#L440, https://github.com/evothings/evothings-studio/blob/2.1.0a2/hyper/server/file-server.js#L444 Adding a slash makes it work, but preferably PATH.join() should be used.

Current code that does not work:

	var androidCordovaAppPath =
		mBasePath +
		'../platforms/android/assets/' +
		'www' + path

This works (hard-coded platform to 'android' when testing):

	var androidCordovaAppPath =
		mBasePath +
		'/../platforms/android/assets/' +
		'www' + path

Better solution, not tested though (note that the "missing slash" is not needed when using join):

	var androidCordovaAppPath =
		PATH.normalize(
			PATH.join(
				mBasePath,
				'../platforms/android/assets/',
				'www',
				path))

Conclusion is that this problem can be fixed, but the server needs to be updated to send the correct platform given in the HTTP request.

If it is desirable to keep this functionality is another question, see discussion in this issue: https://github.com/evothings/evothings-doc/issues/91

**Comment by gokr** [comment]
Let's decide this one during Fredrika, I agree with the idea to skip this functionality and instead focus on making it easy to build Viewers. Thus recommend to close.

**Comment by mikaelkindborg** [comment]
Closing issue, supported method for adding custom plugins is to build Evothings Viewer.
