### ISSUE TITLE
Add information about Evothings libraries to the Workbench

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#153]
Add a menu item that links to the documentation with info and download for Evothings libraries.
Make a new separate page for the libraries in our doc structure, not just under APIs.

**Comment by gokr** [comment]
I have now added a separate tab with Libraries similar to Examples. Also loaded from online. Only need a button "Add to app" that let's you add one to an app, or something like that.

**Comment by gokr** [comment]
Done, created another issue for the "Config" part
