### ISSUE TITLE
Add mechanism to push files without reload

### ISSUE THREAD

**Issue by gokr** [evothings/evothings-studio#157]
Peter is working on a little mini framework enabling more fine grained control over viewers. One simple feature this enables is to be able to "push" (via a button or via modified file notification) a file to the viewer without causing a reload of the application on the viewer. The application code should also be able to get a callback so that it can handle this file in whatever the way it would like to, like for example pushing it further via BLE as an OTA firmware update. :)

**Comment by perttikasanenhitseed** [comment]
This could be closed. Works in 2.1 alpha5

**Comment by gokr** [comment]
Works in 2.1.
