### ISSUE TITLE
2.1 alpha: error handling of inserting projects

### ISSUE THREAD

**Issue by perttikasanenhitseed** [evothings/evothings-studio#160]
(Is this the right place for Studio 2.1 alpha issues?)

Adding a project by dragging it to "My Apps" silently fails if the evothings.json has an "app-dir" defined but that directory does not have an index.html file. 

As a side effect doing this makes all the existing projects in "My Apps" invisible (project list building probably fails). Adding the project again with index.html does solve this and all the old projects become visible again.

**Comment by gokr** [comment]
Ah! Yeah, I also noted "silent failing" with other inconsistencies in the evothings.json file - so the first "fix" is to add proper error reporting at least.

**Comment by mikaelkindborg** [comment]
Added error handling in this commit: https://github.com/evothings/evothings-studio/commit/28a4ef73b93d3bb24ab2a624e1d1c5a1f95db4e5
