### ISSUE TITLE
Evothings Studio not working on CentOS 6.7

### ISSUE THREAD

**Issue by psvensson** [evothings/evothings-studio#163]
Linux64 problem;

EvothingsWorkbench: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

**Comment by halindrome** [comment]
Just to be clear, this system DOES have libnotify installed.  And the system says it is up to date.  But it is version 0.5.0.  The .so files available are so.1 and so.1.2.3  

Hope this helps.

**Comment by gokr** [comment]
Could you test out the new 2.1 beta2?
https://evothings.com/download-evothings-studio-beta/

I suspect it works, we are now using electron instead.

**Comment by gokr** [comment]
I am closing this since I don't have a CentOS 6.7 up and running to test on, suspect it works fine now.
