### ISSUE TITLE
EDIT button -> CONFIGURE or SETTINGS

### ISSUE THREAD

**Issue by mazekeeper** [evothings/evothings-studio#184]
The button label in MY APPS called EDIT is confusing as many go there to edit their apps, and that would be CODE instead (which is also confusing, although not quite as much). The current EDIT button should have its name altered to CONFIG, SETTINGS or similar.

**Comment by gokr** [comment]
Renamed to CONFIG. CODE is renamed to FILES. There will also be an EDIT but it will open the app in VSCode for editing, so quite logical :)
