### ISSUE TITLE
opt-in registration as part of the evothingsstudio desktop applications

### ISSUE THREAD

**Issue by ardiri** [evothings/evothings-studio#22]
as part of our "community" communication follow-up, reactivate users and feedback strategy we need to provide a opt-in (not mandatory) option for the end user to provide his contact details (email address)  when the new version is run for the first time promoting that we:

a) may request feedback from users / surveys
b) inform about IoT related activities (competitions, events) that we host
c) tips and tricks, gallery subscription information 

the end user should be able to say "no, not interested" or provide their email address (have a php script on the server) to build a database of email addresses.

**Comment by fredrikeldh** [comment]
Made irrelevant by 2.0.
