### ISSUE TITLE
Application icon on Linux - Making Linux package/installer

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#27]
Task is to investigate and implement the Evothings Workbench application icon on Linux.

To have custom icons on Linux, you can use a .desktop file. However, it seems .desktop needs to be copied to a system folder, and for this some installer is needed. 

Links:
https://github.com/rogerwang/node-webkit/wiki/Icons
https://wiki.archlinux.org/index.php/Desktop_Entries
https://github.com/probonopd/AppImageKit

**Comment by probonopd** [comment]
We have an [AppImage for Atom](https://bintray.com/probono/AppImages/Atom/view#files) up and running, so it would probably be easy to make one for Evothings Studio using a similar [recipe](https://github.com/probonopd/AppImages/blob/master/recipes/atom/Recipe).

**Comment by gokr** [comment]
We use electron packaging now and the icon works fine.

**Comment by probonopd** [comment]
Instead of telling users "Debian deb package 49 MiB, for non deb Linux use alien" you could use the AppImage target for Linux which is the default in the latest electron-builder.

**Comment by mikaelkindborg** [comment]
@probonopd Thanks sounds like AppImage is an interesting technology to investigate. (Sorry that I missed your post on AppImage from Feb 7.)

**Comment by gokr** [comment]
@probonopd Hey! I just noticed you are... the one who developed AppImage, right? Nice! I am just reading up on it - and if its default these days we will surely switch to it for the 2.1.1 release :)
