### ISSUE TITLE
Improve UI of Tools window, clarify script exec and log panes

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#58]
It's not obvious that the top pane in the Tools window is for executing code, and the bottom one is the log output. Make this clearer by for example adding a header "Device log" or "Remote logging" above the log pane, or some other hint about the panes' contents and purpose.

Additionally, consider renaming the Tools window to Debug for clarifying its purpose.

**Comment by psvensson** [comment]
An effort to rework the UI of the workbench is under way and naming of windows will be included there
