### ISSUE TITLE
Cannot select text in the log window while messages are displayed

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#59]
Problem:

If you want to copy text in the log window, that is not possible while new messages are displayed. Selected text becomes unselected when a new message is displayed. This happens also when "Toggle Autoscroll" is enabled (scrolling turned off).

Solution:

The selection is clear likely because the text in the log is updated. This happens also when scrolling is turned off. One solution could be to buffer log messages while scrolling is disabled, and append the buffered messages when scrolling is turned on. But then the user would not see the new messages.
Perhaps rename the button to "Pause logging" or "Toggle Logging"?

A temporary workaround is to run another app that does not display log messages. That would stop new message from being displayed (given that the other app does not display lots of messages!).

**Comment by fredrikeldh** [comment]
Can the event "user starts text selection" be detected? If so, scrolling and appending can be temporarily disabled while selection is in progress.
