### ISSUE TITLE
Preserve project list between versions by keeping it in localStorage.

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#69]
When upgrading Evothings Workbench, the application folder is often first erased, after which the new application folder is put in its place. This deletes the project-list.json file. To preserve the project list, store the project list in localStorage, which physically is stored in the OS:es user folder, which is not deleted when removing the application folder.

**Comment by fredrikeldh** [comment]
An implentation is available in this branch: https://github.com/fredrikeldh/evothings-studio/tree/example-handling

**Comment by divineprog** [comment]
Merged and pushed to branch evothings2.
