### ISSUE TITLE
Add new Examples section to Workbench.

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#71]
As the Workbench project list is growing and increasingly hard to overlook, a new section containing all examples shoud be introduced. This section shall be reached through a tab button at the top.

The section is composed of a static HTML file with a list of examples bundled with the Workbench, and there should be a link to the online gallery of examples (the online gallery items should have download buttons that allows the user to download the examples to the Workbench).

Not all of the examples in the evothings-examples repo should be bundled with the Workbench package, only a selected few. The majority of the examples, and also user-submitted examples, can be downloaded from the online gallery.

The online gallery opens within the Workbench, i.e. within the node-webkit browser, and utilizes the gallery application (code in evothings-gallery repo) which will also be used in Evothings Client and the website, with different view filters and default sorting settings etc.

**Comment by fredrikeldh** [comment]
Partial implementation: https://github.com/fredrikeldh/evothings-studio/tree/example-handling

**Comment by divineprog** [comment]
Branch example-handling merged to branch evothings2.

**Comment by divineprog** [comment]
First version of separation of examples and custom projects have been implemented. Closing this issue for now. Reopen if needed.
