### ISSUE TITLE
Add button: Copy Workbench URL to clipboard

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#72]
It's desirable to easily being able to copy the Workbench URL from the Workbench window and paste it into a browser. This is now possible but is problematic, for example the entire row of text gets selected when moving the selection cursor outside the text area. I suggest adding a button that copies the URL to the clipboard.

**Comment by fredrikeldh** [comment]
evothings-studio requires a Cordova client. Browsers aren't really supported. Closing.
