### ISSUE TITLE
Inform about redirection of log messages.

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#74]
In some cases it's not apparent that console messages are being redirected to the Workbench. To inform the user about that the redirection is active, write a log message to the browser before the redirection is made.

A common scenario is that the client is a browser on the same machine running the Workbench. Because local debugging is easier than remote debugging, the browser console is here probably used. With the console redirection active it's easy to miss messages due to unawareness that they are being redirected to the Workbench.

**Comment by fredrikeldh** [comment]
This is done not by the studio but by the examples (evothings-examples).
