### ISSUE TITLE
Provide method to turn off automatic console redirection.

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#75]
In some cases, e.g. when using the Workbench locally or when remote browser inspection is used, its desirable to be able to turn off the automatic redirection of console messages that the Workbench uses. Add a button/checkbox in the Workbench interface that toggles automatic console redirection.

Alternatively, always show console messages in both the browser and the Workbench.

Related issue: https://github.com/evothings/evothings-studio/issues/74

**Comment by fredrikeldh** [comment]
Like #74, this is done by each example. Issue is irrelevant.
