### ISSUE TITLE
Copy examples to User's folder on Windows (7+) to avoid write access issues.

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#76]
On Windows, if putting the Workbench folder inside the Program Files folder or similar, the example files becomes read-only. This can be alleviated by providing instructions to the user, but to make things easier for the user, the examples files should automatically be put inside the User's folder.

This can be made by either an installer application or by the Workbench. In the case of the Workbench, at first start-up there should be a dialog asking the user where to put the examples files, and the default choice should be the User's folder.

Note: also other folders than the Program Files folder has write-protection. Investigate which folders are not write-protected. This can differ between Windows versions.

**Comment by divineprog** [comment]
Update install instructions on the download page to say that you should unpack into a folder that is not "Program Files", e.g. the user's home directory or the desktop folder.

**Comment by gokr** [comment]
Problem doesn't exist anymore since Workbench 2.0 beta 2 copies examples to a user directory instead of opening them "in place". I just unzipped into Program Files and ran from there, no problem.
