### ISSUE TITLE
No launch in fresh win 7, 8.1, or 10 machines. 

### ISSUE THREAD

**Issue by extractcraftlee** [evothings/evothings-studio#89]
Three laptops fresh out of the box. Cannot launch anything. Dies or generates "failed" errors. Is this still a supported distro?

**Comment by psvensson** [comment]
Hi @extractcraftlee we're currently busy releasing version 2.0 of thw rokbench. Could you see if you get the same errors using the bet2 version of 2.0? 

https://evothings.com/download/

**Comment by gokr** [comment]
Closing this one due to no feedback.
