### ISSUE TITLE
Make examples' documentation accessible through workbench button

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-studio#9]
Each example app in the workbench should have a button that opens its related documentation. This was discussed by the EvoThings staff previously and accepted as a good idea.

**Comment by fredrikeldh** [comment]
Example handling is being modified in connection with 2.0.

**Comment by gokr** [comment]
There is now a Doc button and all examples are now loaded online etc. The URL for docs is in evothings.json for each app. There is also several menu choices to go to online documentation where all Evothings examples are listed.
