### ISSUE TITLE
Fix clients connected counter

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-studio#94]
Make clients connected counter more reliable. This will require rewrite of how clients are handled on the server.

**Comment by divineprog** [comment]
Workbench part of client info (number of connected clients) implemented in this commit: https://github.com/evothings/evothings-studio/commit/7e8207647f9212dd849746712cf48729a5467075

**Comment by mikaelkindborg** [comment]
Working implementation in this commit: https://github.com/evothings/evothings-server/commit/6777f2d3516a4eb1ebd40a080fb8590024c0e8c4
